import Head from "next/head";
import Nav from "../components/Nav";
import Body from "../components/Uploads/Body";

import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>EAF project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo_mark.svg" />
      </Head>
      <main className={styles.main}>
        <Nav />
        <Body />
      </main>
    </div>
  );
}
